### PR TITLE
vue-element-spy

### PR DESCRIPTION
**Pull request by badz0**
This change is [Reviewable](https://reviewable.io/reviews/reviewable/vue-element-spy/1)

### CODE REVIEW

**Review by dhbradshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/vue-element-spy/1)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @badz0, @dhbradshaw, and @pkaminski)

___
*[src/spy-service.js, line 11 at r1](https://reviewable.io/reviews/reviewable/vue-element-spy/1#-MASgwYJAcRwbX_34xFj:-MASgwYJAcRwbX_34xFk:b-e8dsv) ([raw file](https://github.com/reviewable/vue-element-spy/blob/2d65f2180ab1d9755fa73f65dc4781dafb0bebdd/src/spy-service.js#L11)):*
> ```JavaScript
>     this.refreshIntervalId = undefined;
> 
>     this.contextsList = new Map();
> ```

Nit: this looks like a map of lists.  Should it be contextLists instead of contextsList?

**Review by dhbradshaw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/reviewable/vue-element-spy/1)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @badz0 and @pkaminski)

___
*[src/spy-service.js, line 2 at r1](https://reviewable.io/reviews/reviewable/vue-element-spy/1#-MBKdw5T8zhmr7PLiIHb:-MBKdw5UElkSB6y2EY8n:b-2ssq4v) ([raw file](https://github.com/reviewable/vue-element-spy/blob/2d65f2180ab1d9755fa73f65dc4781dafb0bebdd/src/spy-service.js#L2)):*
> ```JavaScript
> const defaultConfig = {
>   greedy: true,
> ```

Not sure if a more explicit title might be better, and if so what it might be.  `offOnExit`? `watchBase`? `watchExit`?
___
*[src/spy-service.js, line 11 at r1](https://reviewable.io/reviews/reviewable/vue-element-spy/1#-MASgwYJAcRwbX_34xFj:-MBKdrI03FOUeYjCFc5F:b-8slmu0) ([raw file](https://github.com/reviewable/vue-element-spy/blob/2d65f2180ab1d9755fa73f65dc4781dafb0bebdd/src/spy-service.js#L11)):*
<details><summary><i>Previously, dhbradshaw (Douglas H. Bradshaw) wrote…</i></summary><blockquote>

Nit: this looks like a map of lists.  Should it be contextLists instead of contextsList?
</blockquote></details>

or maybe just contexts
___
*[src/spy-service.js, line 41 at r1](https://reviewable.io/reviews/reviewable/vue-element-spy/1#-MBKgODG8D0DcpcsTFSR:-MBKgODG8D0DcpcsTFSS:bugqp3x) ([raw file](https://github.com/reviewable/vue-element-spy/blob/2d65f2180ab1d9755fa73f65dc4781dafb0bebdd/src/spy-service.js#L41)):*
> ```JavaScript
>       target = items.find(item => item.el === el);
>       if (target) {
>         context = items;
> ```

Changing the api to allow explicitly named contexts and not have context be bound to the dom will make this more powerful and explicit.  It will also make your code a bit faster and simpler.  You'll have to bump semvar when you do it.

Also, don't forget to add the more detailed readme, which will need to be updated as well.

**Review by dhbradshaw — COMMENTED** [review]
Overall looking quite nice.

> *[Reviewable](https://reviewable.io/reviews/reviewable/vue-element-spy/1#-:-MBKhL048kQKfhVuWLAT:bodpdv6)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @badz0 and @pkaminski)

**Review by dhbradshaw — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/reviewable/vue-element-spy/1)* status: all files reviewed, 3 unresolved discussions (waiting on @badz0 and @pkaminski)

**Review by badz0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/vue-element-spy/1)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @dhbradshaw and @pkaminski)

___
*[src/spy-service.js, line 41 at r1](https://reviewable.io/reviews/reviewable/vue-element-spy/1#-MBKgODG8D0DcpcsTFSR:-MBxqkSQ1s-u5ix_JpI2:b-896fix) ([raw file](https://github.com/reviewable/vue-element-spy/blob/2d65f2180ab1d9755fa73f65dc4781dafb0bebdd/src/spy-service.js#L41)):*
<details><summary><i>Previously, dhbradshaw (Douglas H. Bradshaw) wrote…</i></summary><blockquote>

Changing the api to allow explicitly named contexts and not have context be bound to the dom will make this more powerful and explicit.  It will also make your code a bit faster and simpler.  You'll have to bump semvar when you do it.

Also, don't forget to add the more detailed readme, which will need to be updated as well.
</blockquote></details>

Done.

**Review by dhbradshaw — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/reviewable/vue-element-spy/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Pull request merged**
